import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import FloatChatButton from "@/components/FloatChatButton";
import { ProductsProvider } from "@/context/ProductsContext";
import { CartProvider } from "@/context/CartContext";
import { CheckoutProvider } from "@/context/CheckoutContext";
import { AuthProvider } from "@/context/AuthContext";
import { WebSocketProvider } from "@/context/WebSocketContext";
import ToasterProvider from "@/components/ToasterProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CheckoutProvider>
          <AuthProvider>
            <WebSocketProvider>
              <CartProvider>
                <ProductsProvider>
                  <div className="flex flex-col min-h-screen">
                    <Navbar />
                    {children}
                    <Footer />
                  </div>
                  <FloatChatButton />
                  <ToasterProvider />
                </ProductsProvider>
              </CartProvider>
            </WebSocketProvider>
          </AuthProvider>
        </CheckoutProvider>
      </body>
    </html>
  );
}
